version: '3'
services:
  app:
    build: ./app
    volumes:
        - /var/run/docker.sock/:/var/run/docker.sock
        - ./app/log:/app/log
    ports:
        - 8080:8000
    links:
        - db:db
    depends_on:
        - db
        - gesis_rank_pyserini_base
        - gesis_rec_pyserini
    environment:
        - RANKSYS_LIST=gesis_rank_pyserini_base
        - RANKSYS_BASE=livivo_base
        - RECSYS_LIST=gesis_rec_pyserini
        - RECSYS_BASE=gesis_rec_pyserini
        - STELLA_SERVER_ADDRESS=https://lilas.stella-project.org
        - STELLA_SERVER_USER=gesis@stella-project.org
        - STELLA_SERVER_PASS=pass
        - STELLA_SERVER_USERNAME=GESIS
        - INTERLEAVE=True
        - BULK_INDEX=True
        - DELETE_SENT_SESSION=True
        - INTERVAL_DB_CHECK=3
        - SESSION_EXPIRATION=6
  db:
    image: postgres
    ports:
        - 5432:5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
  gesis_rank_pyserini_base:
    build: https://github.com/stella-project/gesis_rank_pyserini_base.git
    container_name: gesis_rank_pyserini_base
    volumes:
        - ./data/:/data/
        - ./index/gesis_rank_pyserini_base:/index/
  gesis_rec_pyserini:
    build: https://github.com/stella-project/gesis_rec_pyserini.git
    container_name: gesis_rec_pyserini
    volumes:
        - ./data/:/data/
        - ./index/gesis_rec_pyserini:/index/
