FROM python:3.9

RUN apt-get update && apt-get install -y libpq-dev gcc


WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

CMD ["flask", "run", "--host=0.0.0.0", "--port=8000"]